import Male from "../public/Male.png";

export const studentsArr = [
  {
    image: Male,
    name: "Rachit Rajput",
    ID: 53424,
    Class: 4,
    Active: "Yesterday",
    Courses: 8,
  },
  {
    image: Male,
    name: "Rachit Rajput",
    ID: 53424,
    Class: 4,
    Active: "Yesterday",
    Courses: 8,
  },
  {
    image: Male,
    name: "Rachit Rajput",
    ID: 53424,
    Class: 4,
    Active: "Yesterday",
    Courses: 8,
  },
  {
    image: Male,
    name: "Rachit Rajput",
    ID: 53424,
    Class: 4,
    Active: "Yesterday",
    Courses: 8,
  },
  {
    image: Male,
    name: "Rachit Rajput",
    ID: 53424,
    Class: 4,
    Active: "Yesterday",
    Courses: 8,
  },
  {
    image: Male,
    name: "Rachit Rajput",
    ID: 53424,
    Class: 4,
    Active: "Yesterday",
    Courses: 8,
  },
  {
    image: Male,
    name: "Rachit Rajput",
    ID: 53424,
    Class: 4,
    Active: "Yesterday",
    Courses: 8,
  },
  {
    image: Male,
    name: "Rachit Rajput",
    ID: 53424,
    Class: 4,
    Active: "Yesterday",
    Courses: 8,
  },
];
